absolute_urls: false
timezone: America/Chicago
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: true
force_lowercase_urls: true
custom_base_url: 'https://www.webuxr.com'
username_regex: '^[a-z0-9_-]{3,16}$'
pwd_regex: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}'
intl_enabled: true
languages:
  include_default_lang: true
  pages_fallback_only: false
  translations: false
  translations_fallback: false
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: quark
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'Y-m-d H:i'
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: true
  never_cache_twig: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: true
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - html
    - htm
    - json
    - xml
    - txt
    - rss
    - atom
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '302'
  redirect_trailing_slash: false
  ignore_files:
    - .DS_Store
    - Thumbs.db
    - .gitkeep
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  purge_at: '0 4 * * *'
  clear_at: '0 3 * * *'
  clear_job_type: standard
  clear_images_by_default: true
  cli_compatibility: true
  lifetime: 604800
  gzip: true
  allow_webserver_gzip: true
  redis:
    socket: /var/run/redis/redis-server.pid
    server: 127.0.0.1
    password: inUmenqrueISdDnH6HPSbZTI8/wtkAIMTBCQudLKk9tk7SHwSftrLBNvQwl1/EsUHlPjss9c4wUeF9o8
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: true
  undefined_functions: true
  undefined_filters: true
  umask_fix: true
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: false
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: 1
  log: true
log:
  handler: syslog
  syslog:
    facility: local6
debugger:
  enabled: true
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 60
  cache_all: false
  cache_perms: '0775'
  debug: false
  auto_fix_orientation: false
media:
  enable_media_timestamp: true
  auto_metadata_exif: false
  upload_limit: 2097152
session:
  enabled: true
  initialize: true
  timeout: 1800
  name: grav-webuxr-www
  uniqueness: salt
  secure: false
  httponly: true
  split: true
gpm:
  releases: stable
  method: fopen
  verify_peer: true
  official_gpm_only: true
accounts:
  type: data
  storage: file
strict_mode:
  yaml_compat: true
  twig_compat: true
